<?php
/**
 * Static activities catalog helpers.
 *
 * @package AjinsafroTravelerHome
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! function_exists( 'ajth_get_static_activities_catalog' ) ) {
	/**
	 * Returns the temporary static catalog for the activities landing page.
	 *
	 * The array shape is intentionally close to the future CRUD payload so the
	 * front-end can be reused with minimal changes later.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	function ajth_get_static_activities_catalog() {
		$activities = array(
			array(
				'id'                 => 101,
				'title'              => 'Quad dans la Palmeraie de Marrakech',
				'country'            => 'Maroc',
				'city'               => 'Marrakech',
				'category'           => 'Aventure',
				'duration_hours'     => 2,
				'duration_label'     => '2 heures',
				'price'              => 250,
				'image'              => 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&w=1200&q=80',
				'featured'           => true,
				'rating'             => 4.8,
				'reviews'            => 189,
				'includes'           => array( 'Guide', 'Casque', 'Transport' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => 'A la une',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 102,
				'title'              => 'Excursion bateau a Dakhla',
				'country'            => 'Maroc',
				'city'               => 'Dakhla',
				'category'           => 'Mer & bateau',
				'duration_hours'     => 5,
				'duration_label'     => 'Demi-journee',
				'price'              => 400,
				'image'              => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
				'featured'           => true,
				'rating'             => 4.9,
				'reviews'            => 142,
				'includes'           => array( 'Guide', 'Transport', 'Assurance' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => false,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => 'A la une',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 103,
				'title'              => 'Tour culturel a Istanbul',
				'country'            => 'Turquie',
				'city'               => 'Istanbul',
				'category'           => 'Culture',
				'duration_hours'     => 8,
				'duration_label'     => 'Journee complete',
				'price'              => 520,
				'image'              => 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=1200&q=80',
				'featured'           => true,
				'rating'             => 4.7,
				'reviews'            => 211,
				'includes'           => array( 'Guide', 'Billet', 'Transport' ),
				'availability'       => 'Confirme',
				'available_today'    => false,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => 'A la une',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 104,
				'title'              => 'Safari desert a Dubai',
				'country'            => 'Emirats Arabes Unis',
				'city'               => 'Dubai',
				'category'           => 'Aventure',
				'duration_hours'     => 7,
				'duration_label'     => 'Demi-journee',
				'price'              => 690,
				'image'              => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
				'featured'           => true,
				'rating'             => 4.9,
				'reviews'            => 276,
				'includes'           => array( 'Guide', 'Transport', 'Assurance' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => 'A la une',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 105,
				'title'              => 'Visite guidee de la medina de Fes',
				'country'            => 'Maroc',
				'city'               => 'Fes',
				'category'           => 'Culture',
				'duration_hours'     => 3,
				'duration_label'     => '3 heures',
				'price'              => 180,
				'image'              => 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f56?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.6,
				'reviews'            => 83,
				'includes'           => array( 'Guide', 'Assurance' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => false,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 106,
				'title'              => 'Kayak lagon et flamants a Dakhla',
				'country'            => 'Maroc',
				'city'               => 'Dakhla',
				'category'           => 'Nature',
				'duration_hours'     => 4,
				'duration_label'     => 'Demi-journee',
				'price'              => 320,
				'image'              => 'https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.8,
				'reviews'            => 67,
				'includes'           => array( 'Guide', 'Assurance', 'Transport' ),
				'availability'       => 'Confirme',
				'available_today'    => false,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 107,
				'title'              => 'Balade gourmande au port de Tanger',
				'country'            => 'Maroc',
				'city'               => 'Tanger',
				'category'           => 'Gastronomie',
				'duration_hours'     => 3,
				'duration_label'     => '3 heures',
				'price'              => 210,
				'image'              => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.5,
				'reviews'            => 54,
				'includes'           => array( 'Guide', 'Billet' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => false,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 108,
				'title'              => 'Croisiere sunset sur la corniche de Casablanca',
				'country'            => 'Maroc',
				'city'               => 'Casablanca',
				'category'           => 'Mer & bateau',
				'duration_hours'     => 2,
				'duration_label'     => '2 heures',
				'price'              => 290,
				'image'              => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.4,
				'reviews'            => 49,
				'includes'           => array( 'Guide', 'Assurance' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 109,
				'title'              => 'Surf coaching a Taghazout Agadir',
				'country'            => 'Maroc',
				'city'               => 'Agadir',
				'category'           => 'Sport',
				'duration_hours'     => 6,
				'duration_label'     => 'Demi-journee',
				'price'              => 350,
				'image'              => 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.8,
				'reviews'            => 101,
				'includes'           => array( 'Guide', 'Transport', 'Assurance' ),
				'availability'       => 'Confirme',
				'available_today'    => false,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 110,
				'title'              => 'Journee bleue a Chefchaouen',
				'country'            => 'Maroc',
				'city'               => 'Chefchaouen',
				'category'           => 'Famille',
				'duration_hours'     => 8,
				'duration_label'     => 'Journee complete',
				'price'              => 260,
				'image'              => 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.7,
				'reviews'            => 72,
				'includes'           => array( 'Guide', 'Transport', 'Assurance' ),
				'availability'       => 'Disponible',
				'available_today'    => false,
				'instant_booking'    => false,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 111,
				'title'              => 'Vol en montgolfiere a Cappadoce',
				'country'            => 'Turquie',
				'city'               => 'Cappadoce',
				'category'           => 'Nature',
				'duration_hours'     => 3,
				'duration_label'     => '3 heures',
				'price'              => 980,
				'image'              => 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.9,
				'reviews'            => 193,
				'includes'           => array( 'Guide', 'Transport', 'Assurance' ),
				'availability'       => 'Confirme',
				'available_today'    => false,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => 'Populaire',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 112,
				'title'              => 'Croisiere cote turquoise a Antalya',
				'country'            => 'Turquie',
				'city'               => 'Antalya',
				'category'           => 'Mer & bateau',
				'duration_hours'     => 8,
				'duration_label'     => 'Journee complete',
				'price'              => 560,
				'image'              => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.7,
				'reviews'            => 118,
				'includes'           => array( 'Guide', 'Transport', 'Billet' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 113,
				'title'              => 'Bike architecture a Barcelone',
				'country'            => 'Espagne',
				'city'               => 'Barcelone',
				'category'           => 'Culture',
				'duration_hours'     => 4,
				'duration_label'     => 'Demi-journee',
				'price'              => 430,
				'image'              => 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.6,
				'reviews'            => 86,
				'includes'           => array( 'Guide', 'Billet' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 114,
				'title'              => 'Tapas et rooftops a Madrid',
				'country'            => 'Espagne',
				'city'               => 'Madrid',
				'category'           => 'Gastronomie',
				'duration_hours'     => 3,
				'duration_label'     => '3 heures',
				'price'              => 370,
				'image'              => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.5,
				'reviews'            => 74,
				'includes'           => array( 'Guide', 'Billet' ),
				'availability'       => 'Confirme',
				'available_today'    => false,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 115,
				'title'              => 'Flamenco experience a Seville',
				'country'            => 'Espagne',
				'city'               => 'Seville',
				'category'           => 'Culture',
				'duration_hours'     => 2,
				'duration_label'     => '2 heures',
				'price'              => 310,
				'image'              => 'https://images.unsplash.com/photo-1515442261605-65987783cb6a?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.8,
				'reviews'            => 92,
				'includes'           => array( 'Guide', 'Billet' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => true,
				'with_guide'         => false,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 116,
				'title'              => 'Croisiere privee sur la Seine',
				'country'            => 'France',
				'city'               => 'Paris',
				'category'           => 'Famille',
				'duration_hours'     => 2,
				'duration_label'     => '2 heures',
				'price'              => 720,
				'image'              => 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.7,
				'reviews'            => 164,
				'includes'           => array( 'Guide', 'Billet', 'Assurance' ),
				'availability'       => 'Confirme',
				'available_today'    => false,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 117,
				'title'              => 'Evasion cote d Azur en bateau',
				'country'            => 'France',
				'city'               => 'Nice',
				'category'           => 'Mer & bateau',
				'duration_hours'     => 6,
				'duration_label'     => 'Demi-journee',
				'price'              => 610,
				'image'              => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.8,
				'reviews'            => 105,
				'includes'           => array( 'Guide', 'Transport', 'Assurance' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => false,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 118,
				'title'              => 'Jet ski au large de Dubai Marina',
				'country'            => 'Emirats Arabes Unis',
				'city'               => 'Dubai',
				'category'           => 'Sport',
				'duration_hours'     => 2,
				'duration_label'     => '2 heures',
				'price'              => 540,
				'image'              => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.8,
				'reviews'            => 97,
				'includes'           => array( 'Guide', 'Assurance', 'Billet' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 119,
				'title'              => 'Musee et grande mosquee a Abu Dhabi',
				'country'            => 'Emirats Arabes Unis',
				'city'               => 'Abu Dhabi',
				'category'           => 'Culture',
				'duration_hours'     => 8,
				'duration_label'     => 'Journee complete',
				'price'              => 580,
				'image'              => 'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.7,
				'reviews'            => 133,
				'includes'           => array( 'Guide', 'Transport', 'Billet' ),
				'availability'       => 'Confirme',
				'available_today'    => false,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 120,
				'title'              => 'Cours de cuisine marocaine a Marrakech',
				'country'            => 'Maroc',
				'city'               => 'Marrakech',
				'category'           => 'Gastronomie',
				'duration_hours'     => 4,
				'duration_label'     => 'Demi-journee',
				'price'              => 230,
				'image'              => 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.9,
				'reviews'            => 88,
				'includes'           => array( 'Guide', 'Billet', 'Assurance' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 121,
				'title'              => 'Yoga et plage au lever du soleil a Agadir',
				'country'            => 'Maroc',
				'city'               => 'Agadir',
				'category'           => 'Nature',
				'duration_hours'     => 2,
				'duration_label'     => 'Moins de 2 heures',
				'price'              => 160,
				'image'              => 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.6,
				'reviews'            => 43,
				'includes'           => array( 'Guide', 'Assurance' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => false,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 122,
				'title'              => 'Photo walk imperial a Paris',
				'country'            => 'France',
				'city'               => 'Paris',
				'category'           => 'Culture',
				'duration_hours'     => 3,
				'duration_label'     => '3 heures',
				'price'              => 410,
				'image'              => 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.5,
				'reviews'            => 58,
				'includes'           => array( 'Guide', 'Billet' ),
				'availability'       => 'Confirme',
				'available_today'    => false,
				'instant_booking'    => true,
				'with_guide'         => true,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 123,
				'title'              => 'Spa hammam signature a Casablanca',
				'country'            => 'Maroc',
				'city'               => 'Casablanca',
				'category'           => 'Famille',
				'duration_hours'     => 2,
				'duration_label'     => '2 heures',
				'price'              => 340,
				'image'              => 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.4,
				'reviews'            => 37,
				'includes'           => array( 'Guide', 'Assurance' ),
				'availability'       => 'Disponible',
				'available_today'    => true,
				'instant_booking'    => true,
				'with_guide'         => false,
				'transport_included' => false,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 124,
				'title'              => 'Randonnee panoramique a Chefchaouen',
				'country'            => 'Maroc',
				'city'               => 'Chefchaouen',
				'category'           => 'Aventure',
				'duration_hours'     => 9,
				'duration_label'     => 'Journee complete',
				'price'              => 280,
				'image'              => 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.8,
				'reviews'            => 64,
				'includes'           => array( 'Guide', 'Transport', 'Assurance' ),
				'availability'       => 'Confirme',
				'available_today'    => false,
				'instant_booking'    => false,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
			array(
				'id'                 => 125,
				'title'              => 'Escapade golf premium a Abu Dhabi',
				'country'            => 'Emirats Arabes Unis',
				'city'               => 'Abu Dhabi',
				'category'           => 'Sport',
				'duration_hours'     => 6,
				'duration_label'     => 'Demi-journee',
				'price'              => 890,
				'image'              => 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=1200&q=80',
				'featured'           => false,
				'rating'             => 4.6,
				'reviews'            => 29,
				'includes'           => array( 'Guide', 'Transport', 'Billet' ),
				'availability'       => 'Disponible',
				'available_today'    => false,
				'instant_booking'    => false,
				'with_guide'         => true,
				'transport_included' => true,
				'badge'              => '',
				'url'                => '#',
				'booking_url'        => '#',
			),
		);

		return apply_filters( 'ajth_static_activities_catalog', $activities );
	}
}

if ( ! function_exists( 'ajth_get_activities' ) ) {
	/**
	 * Returns a limited list of activities for the front-end.
	 *
	 * @param int   $limit Number of items to return.
	 * @param array $args  Optional future overrides. Kept for CRUD compatibility.
	 * @return array<int, array<string, mixed>>
	 */
	function ajth_get_activities( $limit = 12, array $args = array() ) {
		$items = ajth_get_static_activities_catalog();
		$items = apply_filters( 'ajth_activities_items', $items, $args );

		return array_slice( array_values( $items ), 0, max( 1, (int) $limit ) );
	}
}
